// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVOuje8BKUMYWmzuhXrVGdNk3Eud3FWM',
    appId: '1:1076896286143:android:f18716b627fbc7c1554d0a',
    messagingSenderId: '1076896286143',
    projectId: 'gardengree-2b915',
    databaseURL: 'https://gardengree-2b915-default-rtdb.firebaseio.com',
    storageBucket: 'gardengree-2b915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcQA3L6tzTURbO2bdGZRzqGT7nJaXOPwg',
    appId: '1:1076896286143:ios:be794dd21110a7e0554d0a',
    messagingSenderId: '1076896286143',
    projectId: 'gardengree-2b915',
    databaseURL: 'https://gardengree-2b915-default-rtdb.firebaseio.com',
    storageBucket: 'gardengree-2b915.firebasestorage.app',
    iosClientId: '1076896286143-nm93fmnt0up375vfgmg5jqn0aauslg5n.apps.googleusercontent.com',
    iosBundleId: 'com.siddhi.gromart.store',
  );

}