// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKjz6rt7G7ZlpbW0S8g6M6m9PMVz_YAg',
    appId: '1:1076896286143:android:4457b32c439959ee554d0a',
    messagingSenderId: '1076896286143',
    projectId: 'gardengree-2b915',
    databaseURL: 'https://gardengree-2b915-default-rtdb.firebaseio.com',
    storageBucket: 'gardengree-2b915.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMRA_-YrJ3EFSfKa5__2ViZFqQ0ttO48',
    appId: '1:1076896286143:ios:4bf462b2733c85ce554d0a',
    messagingSenderId: '1076896286143',
    projectId: 'gardengree-2b915',
    databaseURL: 'https://gardengree-2b915-default-rtdb.firebaseio.com',
    storageBucket: 'gardengree-2b915.firebasestorage.app',
    iosClientId: '1076896286143-ssehcrmjead86mtcv57e0uacijqtcgl0.apps.googleusercontent.com',
    iosBundleId: 'com.garden.green.store.app',
  );

}